### ISSUE TITLE
Copy/Paste of settings

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tHashRow#11]
To transfer all settings (especially the column based) from one thashRow Component to another, it would be nice to have some copy paste buttons.

**Comment by jlolling** [comment]
Yes, that would be great. Unfortunately I have no chance to do that. 
I cannot introduce any code at this stage.
The only thing I could do is to compress all information into the comment field in the schema and we could this way use the schema export / import to transfer the configuration.
