### ISSUE TITLE
Value for null result

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tHashRow#4]
It should be possible to define the output Hashvalue when all incoming Elements are null.
In data vault this would be 0x000000000000000000000000000000000  (got null but expected something else) or 0xffffffffffffffffffffffffffffff (got Null but thats ok).
But its probably better and easear to just add a free text field parameter.

**Comment by jlolling** [comment]
I will add this feature. It sounds pretty important. I will add a text field in which you can setup the "All-Null" value.

**Comment by mattywausb** [comment]
Feature is in the actual release
