### ISSUE TITLE
Option to define delimiter

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tHashRow#6]
It shoul be possible to declare the delimiter string, used für assembling the elements to the string.

**Comment by jlolling** [comment]
Yes, this will be included in the next version.

**Comment by rbtrtr** [comment]
I have forked your component and added this feature among other things. Please have a look and let me know if I should create a pull request.

**Comment by jlolling** [comment]
Hi Robert, I am very happy to have help here! Of course I will accept pull requests. Please take care the component is with its default settings compatible with the current version.
Best regards
Jan

**Comment by mattywausb** [comment]
Feature is in the actual release
