### ISSUE TITLE
base64 encoding option

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tHashRow#9]
Instead of encoding the hash value as a hexadecimal string representation there should be the possibility of encoding it as a base64 string representation (defined in RFC 4648 https://tools.ietf.org/html/rfc4648). This leads to smaller strings with the same information.

**Comment by jlolling** [comment]
Ok I will add this in the next release.

**Comment by mattywausb** [comment]
Solved in 1.5
